### ISSUE TITLE
hard coded include links cause problems in external apps

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#11]
The CamImage.h file has a hard-coded directory reference for an included file. This should be set with a project variable. 

 #include "../Buffer/BaseContainer.h"

**Comment by sfeller** [comment]
Fixed in commit af82a15. Need to be tested in windows. Linux test passes.

**Comment by sfeller** [comment]
This works in the master branch on windows in cc0b3ff..1cfb42f. Need to verify one more time in Linux prior to closing. @paigesullivan, it's all yours.

**Comment by paigesullivan** [comment]
Works in the master branch in Linux

**Comment by sfeller** [comment]
Missed one in camimage. Re-opening

**Comment by sfeller** [comment]
Should be fixed in commit ff18b8cf044676b9167b1e4467e3cf8ae7815828. Need to verify in Linux

**Comment by paigesullivan** [comment]
Works in master branch in Linux

**Comment by sfeller** [comment]
This passes all tests. Closing
