### ISSUE TITLE
JPEG methods

### ISSUE THREAD

**Issue by paigesullivan** [Aqueti/atl#13]
pushed getImage, loadJPEG and saveJPEG methods in ImageContainer.cpp to paigetests

**Comment by sfeller** [comment]
Need to change current testJPEG.jpeg into testJPEG.json (for metadata), move function into the class, and write buffer as the testJPEG.jpeg file.

**Comment by paigesullivan** [comment]
changes made. pushed to paigetests

**Comment by camerongivler** [comment]
merged into master
