### ISSUE TITLE
Image container test failed running valgrind with ImageContainer Test Failed!

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#19]
Seems like it is an issue with the jpeg read/write failure. Need to make a more informative message and fix problem.

Output:
`
./INSTALL/bin/ATLTest

Closing socket 40. Sent 2 and received 0 messages
Closing socket 7. Sent 0 and received 100 messages
All tests completed successfully!
sfeller@red:~/develop/Aqueti/atl/build$ valgrind ./INSTALL/bin/ATLTest -v
==29180== Memcheck, a memory error detector
==29180== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==29180== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==29180== Command: ./INSTALL/bin/ATLTest -v
==29180== 
Timer will not be tested
Testing TSQueue
Peek failed!
Peek failed!
Time: 0.120597
Testing BaseBuffer
Testing extended buffer
Testing BaseContainerMetadata
Testing BaseContainer
Testing TSArray
Testing BaseContainerArrayMetadata
Testing BaseContainerArray
Testing ImageMetadata
Testing ImageContainer
sh: 1: cannot create test/test.tmp: Directory nonexistent
Unable to save PFM for mode 1
Max-write: 0
Create Max: 0.996094
Max-write: 0.996094
jpeg read/write failure 66
ImageContainer Test Failed!
==29180== 
==29180== HEAP SUMMARY:
==29180==     in use at exit: 0 bytes in 0 blocks
==29180==   total heap usage: 1,115 allocs, 1,115 frees, 22,696,566 bytes allocated
==29180== 
==29180== All heap blocks were freed -- no leaks are possible
==29180== 
==29180== For counts of detected and suppressed errors, rerun with: -v
==29180== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)`

**Comment by paigesullivan** [comment]
Failure was a result of valgrind creating different timestamps for the ids of the metadata I was comparing. It now doesn't return false so the rest of the tests can run

**Comment by sfeller** [comment]
Fixed is master based on latest test. Closing
