### ISSUE TITLE
WriteTest gives Segmentation Fault when Block Size is greater than 4MB

### ISSUE THREAD

**Issue by yrsong15** [Aqueti/atl#21]
WriteTest works fine on block sizes of 4MB or less, but once block size exceeds 4MB it gives a segmentation fault (the compiling process using make works fine, but the output is a seg fault).

**Comment by yrsong15** [comment]
The issue seems to be in the following line of code:
`char buffer[bufSize]`
where bufSize is the block size, originally defined as:
`uint64_t bufSize = 4194304;`

**Comment by sfeller** [comment]
Verify that the variable is the size you expect (it may not be the same as defined). Run under valgrind (ask Paige and document how if you don't know). Let me know if you have trouble.

**Comment by yrsong15** [comment]
Issue has been resolved by dynamically allocating the variable "buffer" so that it can accept larger numbers. Ready to be tested via Valgrind.

**Comment by yrsong15** [comment]
Test results of valgrind:
`==30878== 
==30878== HEAP SUMMARY:
==30878==     in use at exit: 0 bytes in 0 blocks
==30878==   total heap usage: 215 allocs, 215 frees, 16,840,046 bytes allocated
==30878== 
==30878== All heap blocks were freed -- no leaks are possible
==30878== 
`
No memory leaks detected. Ready to be pushed to master branch.

**Comment by camerongivler** [comment]
Merged into master
