### ISSUE TITLE
Double compile 

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/atl#24]
Why does ATL compile two libraries: ATL and ATL_static?  It seems like it would be more efficient to just choose one.  When will we ever need both?

**Comment by sfeller** [comment]
We prefer the static. The normal ATL would by dynamically linked. Options are left in for flexibility.

**Comment by camerongivler** [comment]
Okay.  It seems like for the sake of compile times it would be better to just choose one, but if that's not possible, I'll close the issue

**Comment by sfeller** [comment]
Make the a CMAKE option to select. Use static by default.

**Comment by camerongivler** [comment]
implemented on branch issue25

**Comment by camerongivler** [comment]
merged to `master`
