### ISSUE TITLE
Camera ID should be string, not integer

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/atl#25]
In CamImageMetadata, m_camId needs to be a string to fit with our current model of addressing cameras.

**Comment by camerongivler** [comment]
implemented on branch issue25

**Comment by russell-taylor** [comment]
Hmm... this does not match how I've been coupling things into the Fovea adapter.  It was an integer when I made the port.  Will need to know how to map from an integer in APL to a string for the adapter, so please let me know how the names are chosen.

**Comment by camerongivler** [comment]
The names are chosen based on the serial number of the camera, which could potentially contain characters, rather than simply numbers.  FlyCapture uses a 64-bit unsigned int for its serial numbers, so at least for now we can just cast the string to an integer.

**Comment by camerongivler** [comment]
fixed in `issue25` and merged to `master`.
