### ISSUE TITLE
BaseServer crashes with SIGPIPE after 2 clients have closed and a third has been opened

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/atl#28]
This is due to the fact that the server never closes sockets with clients who have closed their end of the connection.  I have made several changes to BaseServer and SocketServer on branch issue25 which address this.  Most of what needed done was simply checking return codes and errno more closely and closing sockets that return errors (broken pipe).

**Comment by sfeller** [comment]
Cameron, since you've already made said changes (and I'm semi-retired), I'll reassign to you. Sounds like we need to have @paigesullivan work out some better testing once we know what to test for.

**Comment by camerongivler** [comment]
I'll take it over.  You might want to check over it though.  SampleServer and SocketTerminal both work now, but JsonServer and JsonClient don't.  I get a divide by 0 error in ExtendedBuffer now at the exact same time as I previously got the SIGPIPE.

**Comment by sfeller** [comment]
Cameron, when you're done, can you specify a good way to test this within the unit test function. Perhaps @paigesullivan can implement it.

**Comment by sfeller** [comment]
Taking back over...

**Comment by camerongivler** [comment]
Current status: No crashing, no divide by 0 error; server exits cleanly.  Old sockets, however, are closed but not removed from the map, causing the map to grow every time a client is added, but never shrink again when clients are removed.  In addition, there are specific cases of spinning when waiting for data.  This unnecessary spinning should be avoided.  I will look for places to add sleeps.

**Comment by camerongivler** [comment]
Fixed the looping with sleep(0.05)

**Comment by russell-taylor** [comment]
You can use select() to wait for connections on sockets,avoiding spinning altogether.

**Comment by sfeller** [comment]
We are using select. I'll check into the looping. May be an issue with the select timeout

**Comment by sfeller** [comment]
Main loop only executes once per timeout. Not looping

**Comment by camerongivler** [comment]
If you do a print in the do-while loop and run a test you'll see that it spins a lot.  Unless your fix also fixed this issue

**Comment by sfeller** [comment]
This is fixed in the issue28 branch. Passing to Cameron to further validate in the context of the command sender/receiver code (#25).

**Comment by camerongivler** [comment]
Fixed in issue28 and merged to master.  Spinning fixed by adding 50ms timeout to `select()`
