### ISSUE TITLE
Not all tcc functionality is tested

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#3]
This manifests itself when external applications access ExtendedBuffer and other functions that are tested, they generate errors. Clearly this code isn't part of the default compile. More unit testing required.

**Comment by paigesullivan** [comment]
pushed to branch issue3. Ready to test

**Comment by camerongivler** [comment]
What has been tested and what still needs to be tested?

**Comment by paigesullivan** [comment]
ExtendedBuffer and TSQueue have been modified and work in the test branch, so need to be tested in master

**Comment by paigesullivan** [comment]
It should be up to date now. Worked in my branch

**Comment by camerongivler** [comment]
paigetests merged into master
