### ISSUE TITLE
BaseContainer Warning

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#32]
BaseContainer generated warning on line 610. Need to pass in a true string.
``
BaseContainer.cpp:610:27: warning: conversion from string literal to
      'char *' is deprecated [-Wc++11-compat-deprecated-writable-strings]
              container.setMagic("Magic\n", 7);
```

**Comment by paigesullivan** [comment]
warning fixed and pushed to branch issue32

**Comment by camerongivler** [comment]
Warning gone, passes unit tests.  Merging with master.
