### ISSUE TITLE
SampleImageSource and SampleImageSink data error

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#34]
SampleImageSource is receiving invalid data in it's handleMessage function. Not sure if it's a sender or receiver issue.

**Comment by sfeller** [comment]
Fixed. Will run into problems if we stream to quickly with dropped packets. May need to revisit how dropped packets are handles. Issue was due to a memcmp checking images are matched but images had different IDs. Cameron, I'll let you merge.

**Comment by camerongivler** [comment]
Merged

**Comment by sfeller** [comment]
Forgot to push a final change. Need to merge commit 9e94f149f994c60a60a3c8d3c08a55566111c1c0

**Comment by camerongivler** [comment]
done
