### ISSUE TITLE
ImageServer and ImageSocket crash with too much data

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/atl#37]
ImageServer and Socket need to be able to handle data overloads

**Comment by camerongivler** [comment]
If it matters at all, I've found that the overload happens right around 120 fps, on localhost

**Comment by sfeller** [comment]
The sockets no longer crash directly, but this does cause headaches without throttling. Needs to be implemented as part of the ImageSocket. Probably by adding a small sleep whenever a failed write occurs. Handing back over to @camerongivler since I'm out for the next few days.

**Comment by camerongivler** [comment]
This has been fixed.  Only one image can be sent at a time.
