### ISSUE TITLE
CommandServer/Client seems to be dropping data

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#38]
Need to figure out what data is getting lost on the server side.

**Comment by camerongivler** [comment]
Only happens over network connections - not on localhost.  Very likely due to the fact that we are ignoring the number of bytes received and instead assuming we received 1024.  This could cause data that was previously in the buffer to be copied into the new data.

**Comment by sfeller** [comment]
Return code from sendData was not handled correctly. Not sure this is a direct cause of the problem, but may provide a clue

**Comment by sfeller** [comment]
Was using recv instead of noint_block_read for some reason. This would cause the issue since a read may be interrupted

**Comment by sfeller** [comment]
Re-worked some package stuff. Need further testing, but have a baseline implementation

**Comment by camerongivler** [comment]
what is the status of the issue38 branch?

**Comment by sfeller** [comment]
It is working version of master either some additional comments
Sent using OWA for iPhone
________________________________

**Comment by sfeller** [comment]
Merged with #40 branch. Both are ready to validate:

**Comment by sfeller** [comment]
Fixed with commit 85637ea10c00a38397c660bdb6200e5ae33ac161
