### ISSUE TITLE
ATL Won't compile. Looks related to the LruCache

### ISSUE THREAD

**Issue by alexvoytik** [Aqueti/atl#39]
-- Installing: /home/mosaic/build/atl/ATL-prefix/src/ATL-build/INSTALL/include/atl/Thread.h
-- Installing: /home/mosaic/build/atl/ATL-prefix/src/ATL-build/INSTALL/include/atl/Timer.h
-- Installing: /home/mosaic/build/atl/ATL-prefix/src/ATL-build/INSTALL/include/atl/TSQueue.tcc
CMake Error at cmake_install.cmake:72 (FILE):
  file INSTALL cannot find "/home/mosaic/src/atl/TSQueue/LruCache.tcc".

**Comment by camerongivler** [comment]
oops. fixed
