### ISSUE TITLE
ImageServer must override SocketServer's Initialize function

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/atl#40]
the Initialize function asks for a callback with an ExtendedBuffer parameter.  ImageServer calls a callback with a CamImage.  ImageServer needs to set that callback itself (by overriding the Initialize function) and then request a callback from the user that takes a CamImage.

**Comment by sfeller** [comment]
Ready for test

**Comment by sfeller** [comment]
Complete with commit 85637ea10c00a38397c660bdb6200e5ae33ac161
