### ISSUE TITLE
need to implement container conversion functions for all BaseContainer derivatives

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#41]
Need to impelement a function to convert between container types. This function should be global but maintained within the source code for each container class. CamImage has implemented a convertBaseContainerToCamImage function. This needs to be done with other containers as well.

**Comment by paigesullivan** [comment]
Pushed to issue41 branch. Ready to be tested with master.

**Comment by sfeller** [comment]
Integrated with commit 5ccd51b
