### ISSUE TITLE
socket received invalid header...

### ISSUE THREAD

**Issue by alexvoytik** [Aqueti/atl#46]
mosaic@webRender:~/build/camerasetupTegras/INSTALL/bin$ ./CamViewer 10001
Server socket:22, port:10001, index: 0
Starting ImageServer on port 10001
Connecting to CommandClient at 10.3.0.1:9005
Hostname: 10.3.0.1:9005
Base socket returning fd of 25
Sender result:60a44c423e031462210107
Socket received an invalid header(����������������,ATLHEAD) of size: 18446744073709551615
Segmentation fault (core dumped)

**Comment by sfeller** [comment]
Looks like this is due to the calling function assuming a negative return code is a failure. Modified and ready to test.

**Comment by sfeller** [comment]
This should be resolved with the issue44 branch and is related to #44

**Comment by sfeller** [comment]
This is implemented in commit 5ccd51b
