### ISSUE TITLE
writeJPEG writes bad jpegs

### ISSUE THREAD

**Issue by dhperkins** [Aqueti/atl#52]
we're writing header of some sort that we shouldn't 
commented that part out. got working code.

**Comment by dhperkins** [comment]
@paigesullivan -- maybe look this over and if we don't need a header, just delete those lines. enough information to decompress and view is already in the jpeg frame header that is internal to the jpeg data. if we need a header, it has to be a field in the jpeg.

**Comment by paigesullivan** [comment]
Looks like the header isn't necessary and those lines can be deleted
