### ISSUE TITLE
Need to delete extraneous branchges

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#6]
Specifically the following: ImageServer, JSONServer, sdf, windows.

Waiting for confirmation from Cameron and Drew before I delete them.

**Comment by camerongivler** [comment]
Done

**Comment by camerongivler** [comment]
May want to check "temp" and "v2.0" before deletion... They are both a few commits in front of master

**Comment by camerongivler** [comment]
temp had no substantive changes.  Steve, could you look over v2.0?  There seem to be a lot of changes and I'm not sure what they do.

**Comment by camerongivler** [comment]
done
