### ISSUE TITLE
Metadata size is inconsistent

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/atl#66]
Particularly in HContainer, metadata size is sometimes defined as the size of just the metadata struct, and other times defined as the size of the metadata struct plus the size of the offset array.  We should make this more consistent.

**Comment by sfeller** [comment]
It should be the size of the metadata struct. The offset indicates the start of the offset array. Number of elements should be enough to calculate the full offset. That's my thoughts.

**Comment by camerongivler** [comment]
Okay.  Sometime when I have a minute I'll fix that.  But I'm not going to do it now because who knows how much it will break

**Comment by camerongivler** [comment]
Just leaving a note that this is also an issue in MapContainer, which is based off HContainer

**Comment by camerongivler** [comment]
Also, GetDataSize() returns `metadata->m_size - metadata->m_metaSize` which would include both the data size plus the offset array... This doesn't seem like what we want since the offset array is not accessible memory.

**Comment by camerongivler** [comment]
This causes an invalid read in `BaseContainer::operator==()`.  I am starting to think we should add the array size in the metaSize

**Comment by sfeller** [comment]
I believe this has been addressed. @camerongivler can you confirm?
