### ISSUE TITLE
BaseContainer is not aligned with blocksize

### ISSUE THREAD

**Issue by camerongivler** [Aqueti/atl#68]
When setting a block size of 4096 bytes and 16384 blocks, an HContainer would be expected to be exactly 16MB in size (67,108,864 bytes).  Instead, the number of bytes saved and loaded from disk is 67,112,960.  This could cause a drop in performance because we are not saving to the native block size of the SSD.

**Comment by uberferg** [comment]
Block size was being followed, block count was off by 1 because we allocate extra block(s) for the metadata.
