### ISSUE TITLE
TestingCommand Server failed 

### ISSUE THREAD

**Issue by paigesullivan** [Aqueti/atl#7]
built and ran test code and got stuck in main loop 

`paige@gray:~/workspace/build/ATL$ ./INSTALL/bin/ATLTest 
Testing CommandServer
Testing command client
Json intitializing on port 9002
-------------sdf output:9002
Server socket: 3, port: 9002, index: 0
Constructing command server on port9002
System already connected on port 9002
Thread threadObject already allocated!
Creating client at: localhost:9002
Constructing command client
Hostname: localhost:9002
Adding connection!
Got a connection
Base socket returning fd of 4
Not connected
message: {"command":{"message1":"test1"},"destId":"bcast","sourceId":"0"}
Received: {
	"command" : {
		"message1" : "test1"
	},
	"destId" : "bcast",
	"sourceId" : "0"
}
Not connected
Not connected
Not connected
Not connected
Not connected
Not connected
Not connected
Not connected
Not connected
message: {"command":{"message1":"test1","shutdown":true},"destId":"bcast","sourceId":"0"}
Received: {
	"command" : {
		"message1" : "test1",
		"shutdown" : true
	},
	"destId" : "bcast",
	"sourceId" : "0"
}
139773670848256: Thread mainLoop
139773670848256: Thread mainLoop
139773670848256: Thread mainLoop
139773670848256: Thread mainLoop
`

**Comment by sfeller** [comment]
THis was an issue with the CommandServer and related to multi-threaded shutdown. The fix is ready to test in the v2.0 branch with release 69a7a5477830d4319baad036da00fb3e423b3969. Once tested, assign back to me and I will merge into master

**Comment by paigesullivan** [comment]
v2.0 fix works and should be ready to merge to master

**Comment by sfeller** [comment]
Merges into master. Ready to verify system wide.

**Comment by sfeller** [comment]
Ready to test with branch cc0b3f of master.

**Comment by sfeller** [comment]
Works with windows

**Comment by paigesullivan** [comment]
Works with Linux
