### ISSUE TITLE
Strange code in SampleServer.cpp:handleMessage()

### ISSUE THREAD

**Issue by russell-taylor** [Aqueti/atl#70]
There is a buffer allocated on the stack, which then gets data copied into it from a parameter that was passed it, which it then passes to a sub-function.

If the purpose was to copy it, then you probably want to allocated it on the heap.  If the purpose is to zero-terminate it, do we know that it does not have internal zeroes?  If neither is intended, why not just pass a pointer to the internal data and length rather than make the copy that then goes out of scope when the function exits?

**Comment by russell-taylor** [comment]
Ditto in SocketTerminal.cpp while () loop in main()

**Comment by camerongivler** [comment]
SampleServer and SocketTerminal are not critical parts of ATL - they're used primarily to demonstrate functionality.  I think more than a little code in these two files is probably pretty ugly.  I'll take a look at it though.

**Comment by camerongivler** [comment]
fixed in commit 2d05aa0
