### ISSUE TITLE
Tests with commandline

### ISSUE THREAD

**Issue by paigesullivan** [Aqueti/atl#8]
updating testing to take arguments (-v and -t) from command line

**Comment by paigesullivan** [comment]
Successfully takes and handles arguments from command line. If enter -v when using valgrind, testTimer won't be tested. Not sure what branch to push it to

**Comment by sfeller** [comment]
Need to add a -h option to print help

**Comment by paigesullivan** [comment]
Now has a -h option to print help

**Comment by sfeller** [comment]
Need to a description and all in SampleServer type format

**Comment by paigesullivan** [comment]
Has descriptions in SampleServer type formal

**Comment by sfeller** [comment]
Merged with master branch. Need to validate then close this ticket

**Comment by paigesullivan** [comment]
master branch works under Linux

**Comment by sfeller** [comment]
WOrks under windows. Closing
