### ISSUE TITLE
testBaseContainer fails on windows due to metadata mismatch

### ISSUE THREAD

**Issue by sfeller** [Aqueti/atl#9]
The testBaseContainer fails with an expected size of 140, not 148 in window unit test using VC2014. This seems to be a version issue since a special directive was needed for previous VC versions

**Comment by sfeller** [comment]
Removed UNIX directive so windows response matches UNIX (and expected response) in v2.0 commit 0e40b1c . UnitTest now passes in windows.

Paige, we need to verify this works in Linux before I merge into master.

**Comment by paigesullivan** [comment]
v2.0 works in Linux so should be ready to merge into master

**Comment by sfeller** [comment]
Now implemented in master. Should be complete
